create table if not exists stops (
  id bigint generated by default as identity primary key,
  time text not null,
  place text not null,
  label text not null,
  sort_order int not null default 0
);

create table if not exists participants (
  id bigint generated by default as identity primary key,
  name text not null,
  stop_id bigint references stops(id) on delete set null,
  note text default '',
  status text not null default 'confirmed' check (status in ('confirmed','waiting')),
  created_at timestamptz default now()
);

alter table stops enable row level security;
alter table participants enable row level security;

create policy "logged in can read stops" on stops for select to authenticated using (true);
create policy "logged in can manage stops" on stops for all to authenticated using (true) with check (true);
create policy "logged in can read participants" on participants for select to authenticated using (true);
create policy "logged in can manage participants" on participants for all to authenticated using (true) with check (true);

insert into stops (time, place, label, sort_order) values
('06:30', 'Daleiden', 'Haltestelle Kirche', 1),
('06:40', 'Arzfeld', 'Haltestelle Physiopraxis', 2),
('06:50', 'Lünebach', 'Haltestelle Brücke', 3),
('07:15', 'Olzheim', 'LKW Parkplatz', 4)
on conflict do nothing;
